name: Monitor Bandi TEST CRON

on:
  workflow_dispatch:
  
  schedule:
    - cron: '*/10 * * * *'
  
jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installa librerie
        run: pip install requests beautifulsoup4 pypdf
      
      - name: Test Sapienza
        run: python monitor.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit storico aggiornato
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add storico.json

          git diff --staged --quiet || git commit -m "Aggiorna storico.json"

          git push
