name: Monitor Bandi

on:
  workflow_dispatch:
  schedule:
    - cron: '15 6 * * 1'

concurrency:
  group: monitor-bandi
  cancel-in-progress: false

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installa librerie
        run: pip install requests beautifulsoup4 pypdf
      
      - name: Test Sapienza
        run: python monitor.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Test UniCamillus
        run: python monitor_unicamillus.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Test Tor Vergata
        run: python monitor_torvergata.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Test Campus Bio-Medico
        run: python monitor_unicampus.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          
      - name: Test Cattolica Roma
        run: python monitor_cattolica.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Test Gemelli IRCCS
        run: python monitor_gemelli.py
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

     # - name: Test Roma Tre
     #   run: python monitor_romatre.py
     #   env:
     #     EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
     #     EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Commit storico aggiornato
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add storico.json
          git add storico_unicamillus.json
          git add storico_torvergata.json
          git add storico_unicampus.json
          git add storico_cattolica.json
          git add storico_gemelli.json
          git add storico_romatre.json

          git diff --staged --quiet || git commit -m "Aggiorna storico.json"

          git push
